language: node_js
node_js:
  - "16"
  
services:
  - postgresql

before_install:
  - npm install -g npm@latest

install:
  - npm install

before_script:
  - psql -c 'create database test_db;' -U postgres
  - mysql -e 'CREATE DATABASE test_db;' -uroot

script:
  - npm test

after_success:
  - echo "All tests passed successfully!"
